# Generated by Django 5.1.3 on 2026-06-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('order_payment', 'Đặt hàng / Thanh toán'), ('account', 'Tài khoản'), ('cart_product', 'Giỏ hàng / Sản phẩm'), ('delivery_warranty', 'Giao hàng / Bảo hành'), ('other', 'Khác')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Chờ xử lý'), ('in_progress', 'Đang xử lý'), ('resolved', 'Đã giải quyết')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
