# Generated by Django 5.1.3 on 2026-06-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='staff_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
