# Generated by Django 5.2.7 on 2025-10-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_status_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên màu')),
            ],
            options={
                'verbose_name': 'Màu sắc',
                'verbose_name_plural': 'Các màu sắc',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='app.color', verbose_name='Màu sắc'),
        ),
    ]
