# Generated by Django 5.2.7 on 2025-10-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_color_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Đỏ'), ('blue', 'Xanh dương'), ('green', 'Xanh lá'), ('yellow', 'Vàng'), ('black', 'Đen'), ('white', 'Trắng'), ('gray', 'Xám')], default='black', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
